name: 🧪 Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - '**.mod'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Check out code
        uses: actions/checkout@v3

      - name: Go Mod hygiene
        run: |
          go clean -modcache
          go mod tidy

      - name: Test
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: go test ./...  